# Generated by Django 2.2.12 on 2022-01-12 07:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220112_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 12, 7, 15, 21, 993038, tzinfo=utc)),
        ),
    ]
