# Generated by Django 2.2.12 on 2022-01-12 07:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 1, 12, 7, 15, 30, 866909, tzinfo=utc)),
        ),
    ]
